### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by zverev** [Crisismap/crisismap-data#1]
### GET /api/categories
```
[
  {
    "id": <String>,
    "name": <String>
  },
  ...
]
```

### GET /api/categories/:categoryId/items
```
[
  "geometry": <GeoJSON>,
  "properties": {
    "id": <String>,
    "title": <String>,
    "description": <String>
  }
  ...
]
```

[GeoJSON spec](https://tools.ietf.org/html/rfc7946#section-3)

**Comment by oleksmarkh** [comment]
moved to https://github.com/Crisismap/crisismap-backend/issues/1
