### ISSUE TITLE
Responsibilities segregation

### ISSUE THREAD

**Issue by oleksmarkh** [Crisismap/crisismap-data#2]
@bkmy43 , let's briefly discuss and agree on out data-related server side structure. While by **back-end** we are used to call the Flask-based API server, the other parts should/could lay down in the following boxes (2 approaches):

1. Current repo is responsible for data processing only (gathering, transformation, loading), meaning it could be renamed to **crisismap-worker**. Correspondingly, we'll need to orchestrate such workers somehow, meaning a basic scheduler/monitor thing - potential **crisismap-orcherstrator** repo, sounds like a set of configs for now. If so, existing `database/` folder seems to belong to **crisismap-backend** - as it would have a notion regarding the PGSQL treasures :) This way, **workers** will simply `POST` to the **back-end**.

2. Another alternative is to share DB access among **workers** and **back-end**, allowing them to read/write and only read correspondingly. This way, `database/` notion should be shared across two apps (two repos), which seems a bit odd, isn't it?

**Comment by bkmy43** [comment]
@oleksmarkh I think crisismap-worker is not the best name, because worker is too general.
May be we should reconsider our decision and merge crisismap-backend and crisismap-database again?

I mean, why should workers whose only task is to get data and write it to the database be stored in separate repository. POST via API might work, but then we would have to batch it somehow... may be for now it is easier to write some very simple python scripts which get the data and put it to the database using pure SQL?

**Comment by oleksmarkh** [comment]
@bkmy43, I support the idea of merging this repo with **back-end**. And yes, **worker** is way too generic indeed. We could call those guys **suppliers** or something (**data-suppliers** is more precise, but we generally deal with data, so this word could be omitted).

The only reason to separate code into a dedicated repo is more or less single responsibility, which also implies deployment.

Basically, we're offering the following chain: **orchestrator/scheduler** (a master node, basically configs) -> **suppliers** (slave nodes - scripts with logs) -> **DB** -> **back-end** (API) -> **front-end** (and possible other clients).

Having this, we're flexible regarding a decision of DB notion - either scoping it to **back-end** exclusively or smashing across **suppliers** and **back-end**. For the beginning we could chose the latter (which is simpler because of having no need to implement `POST` endpoints), and then change our mind to the former one, e.g. in case of facing hassles with simultaneous deployment or something (imagine a need to pause-update-run or even redeploy **suppliers** in case of schema update).

**Comment by bkmy43** [comment]
Those are all valid points, I agree with all of them. The only suggestion I have: how about using "data-provider" instead of "data-supplier"?

**Comment by oleksmarkh** [comment]
@bkmy43, sure - **provider** it is :) Then, actual suppliers (APIs, services) we'll call **sources**. I'm updating the self-descriptive scheme accordingly (see https://github.com/Crisismap/crisismap-backend/issues/3).

**Comment by bkmy43** [comment]
Agreed
